df.read_csv("data.csv")

In [65]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  100 non-null    int64
 1   name         100 non-null    str
 2   age          71 non-null     object
 3   city         87 non-null     str
 4   product      100 non-null    str
 5   price        100 non-null    int64
 6   quantity     100 non-null    int64
dtypes: int64(3), object(1), str(3)
memory usage: 5.6+ KB

In [67]:
df["age"]=pd.to_numeric(df["age"],errors="coerce")
df.head()

   customer_id     name   age     city   product  price  quantity
0            1  Karthik   NaN      NaN    Laptop   1500         3
1            2    Meena   NaN  Madurai     Mouse  56000         2
2            3    Kiran   NaN      NaN     Mouse   2000         2
3            4    Divya   NaN      NaN     Mouse  56000         1
4            5    Kumar  29.0  Chennai  Keyboard   2000         3

In [71]:
df.isnull().sum()

customer_id     0
name            0
age            63
city           13
product         0
price           0
quantity        0
dtype: int64

In [72]:
df["age"]=df["age"].fillna(df["age"].mean())
df.head()

   customer_id     name        age     city   product  price  quantity
0            1  Karthik  25.432432      NaN    Laptop   1500         3
1            2    Meena  25.432432  Madurai     Mouse  56000         2
2            3    Kiran  25.432432      NaN     Mouse   2000         2
3            4    Divya  25.432432      NaN     Mouse  56000         1
4            5    Kumar  29.000000  Chennai  Keyboard   2000         3

In [73]:
df["city"]=df["city"].fillna("unknown")
df.head()

   customer_id     name        age     city   product  price  quantity
0            1  Karthik  25.432432  unknown    Laptop   1500         3
1            2    Meena  25.432432  Madurai     Mouse  56000         2
2            3    Kiran  25.432432  unknown     Mouse   2000         2
3            4    Divya  25.432432  unknown     Mouse  56000         1
4            5    Kumar  29.000000  Chennai  Keyboard   2000         3

In [74]:
df.isnull().sum()

customer_id    0
name           0
age            0
city           0
product        0
price          0
quantity       0
dtype: int64

In [75]:
df

    customer_id     name        age     city     product  price  quantity
0             1  Karthik  25.432432  unknown      Laptop   1500         3
1             2    Meena  25.432432  Madurai       Mouse  56000         2
2             3    Kiran  25.432432  unknown       Mouse   2000         2
3             4    Divya  25.432432  unknown       Mouse  56000         1
4             5    Kumar  29.000000  Chennai    Keyboard   2000         3
..          ...      ...        ...      ...         ...    ...       ...
95           96  Prakash  25.432432    Salem      Laptop   1500         1
96           97    Divya  25.432432    Erode  Headphones   2000         2
97           98      Ram  25.432432  Madurai       Mouse   2000         3
98           99    Deepa  18.000000    Salem    Keyboard  55000         1
99          100  Lakshmi  30.000000    Salem  Headphones   1500         1

[100 rows x 7 columns]

In [78]:
df.drop_duplicates()

    customer_id     name        age     city     product  price  quantity
0             1  Karthik  25.432432  unknown      Laptop   1500         3
1             2    Meena  25.432432  Madurai       Mouse  56000         2
2             3    Kiran  25.432432  unknown       Mouse   2000         2
3             4    Divya  25.432432  unknown       Mouse  56000         1
4             5    Kumar  29.000000  Chennai    Keyboard   2000         3
..          ...      ...        ...      ...         ...    ...       ...
95           96  Prakash  25.432432    Salem      Laptop   1500         1
96           97    Divya  25.432432    Erode  Headphones   2000         2
97           98      Ram  25.432432  Madurai       Mouse   2000         3
98           99    Deepa  18.000000    Salem    Keyboard  55000         1
99          100  Lakshmi  30.000000    Salem  Headphones   1500         1

[100 rows x 7 columns]

In [79]:
df.describe()

       customer_id         age         price    quantity
count   100.000000  100.000000    100.000000  100.000000
mean     50.500000   25.432432  28715.000000    2.050000
std      29.011492    3.289225  27512.554985    0.821123
min       1.000000   18.000000    500.000000    1.000000
25%      25.750000   25.432432   1500.000000    1.000000
50%      50.500000   25.432432  28500.000000    2.000000
75%      75.250000   25.432432  56000.000000    3.000000
max     100.000000   34.000000  57000.000000    3.000000

In [82]:
df["city"]=df["city"].replace("",pd.NA).fillna("unknown")
df

    customer_id     name        age     city     product  price  quantity
0             1  Karthik  25.432432  unknown      Laptop   1500         3
1             2    Meena  25.432432  Madurai       Mouse  56000         2
2             3    Kiran  25.432432  unknown       Mouse   2000         2
3             4    Divya  25.432432  unknown       Mouse  56000         1
4             5    Kumar  29.000000  Chennai    Keyboard   2000         3
..          ...      ...        ...      ...         ...    ...       ...
95           96  Prakash  25.432432    Salem      Laptop   1500         1
96           97    Divya  25.432432    Erode  Headphones   2000         2
97           98      Ram  25.432432  Madurai       Mouse   2000         3
98           99    Deepa  18.000000    Salem    Keyboard  55000         1
99          100  Lakshmi  30.000000    Salem  Headphones   1500         1

[100 rows x 7 columns]

In [83]:
df["city"]=df["city"].replace("Madururai","Madurai")

In [106]:
df["city"]=df["city"].str.strip()
df.isnull().sum()
df["age"]=df["age"].astype(int)
df

    customer_id     name  age     city     product  price  quantity
0             1  Karthik   25  unknown      Laptop   1500         3
1             2    Meena   25  Madurai       Mouse  56000         2
2             3    Kiran   25  unknown       Mouse   2000         2
3             4    Divya   25  unknown       Mouse  56000         1
4             5    Kumar   29  Chennai    Keyboard   2000         3
..          ...      ...  ...      ...         ...    ...       ...
95           96  Prakash   25    Salem      Laptop   1500         1
96           97    Divya   25    Erode  Headphones   2000         2
97           98      Ram   25  Madurai       Mouse   2000         3
98           99    Deepa   18    Salem    Keyboard  55000         1
99          100  Lakshmi   30    Salem  Headphones   1500         1

[100 rows x 7 columns]

In [107]:
df.to_csv("clean_customer_dataset.csv")