In [45]:
import pandas as pd
import matplotlib as plt

In [46]:
df=pd.read_csv("sales.csv")
df

    customer_id     name  age        city     product  price  quantity
0             1     Arun   23     Chennai      Laptop  55000         1
1             2    Kumar   27       Salem       Mouse    500         2
2             3    Divya   22  Coimbatore    Keyboard   1500         1
3             4     Ravi   29     Madurai      Laptop  54000         1
4             5    Priya  NaN     Chennai  Headphones   2000         2
5             6    Manoj   31         NaN       Mouse    450         3
6             7   Anitha   26       Salem    Keyboard   1400         1
7             8   Suresh   28       Erode      Laptop  56000         1
8             9  Karthik          Chennai       Mouse    500         2
9            10    Nisha   23     Madurai  Headphones   2100         1
10           11    Arjun   30  Coimbatore      Laptop  57000         1
11           12    Deepa   25       Erode       Mouse    450         2
12           13    Vijay   27       Salem    Keyboard   1500         1
13           14  Lakshmi   29     Chennai  Headphones   2200         2
14           15      Ram   32         NaN      Laptop  58000         1
15           16    Sneha   24     Madurai       Mouse    500         3
16           17    Kiran   26       Erode    Keyboard   1400         1
17           18    Meena   28       Salem      Laptop  55000         1
18           19  Prakash   31  Coimbatore  Headphones   2000         1
19           20      Anu   22     Chennai       Mouse    450         2
20           21    Varun   27   Madururai    Keyboard   1500         1
21           22  Keerthi   23       Erode  Headphones   2100         1
22           23  Sathish   29       Salem      Laptop  56000         1
23           24    Pooja   24     Chennai       Mouse    500         2
24           25    Gokul   30  Coimbatore    Keyboard   1400         1
25           26    Rekha   26     Madurai  Headphones   2200         2
26           27   Murali   31       Erode      Laptop  57000         1
27           28  Shalini   25      Salem        Mouse    450         2
28           29   Naveen   28     Chennai    Keyboard   1500         1
29           29   Naveen   28     Chennai    Keyboard   1500         1

In [47]:
df.head()

   customer_id   name  age        city     product  price  quantity
0            1   Arun   23     Chennai      Laptop  55000         1
1            2  Kumar   27       Salem       Mouse    500         2
2            3  Divya   22  Coimbatore    Keyboard   1500         1
3            4   Ravi   29     Madurai      Laptop  54000         1
4            5  Priya  NaN     Chennai  Headphones   2000         2

In [48]:
df.shape()

TypeError: 'tuple' object is not callable

In [49]:
df.shape

(30, 7)

In [51]:
df.describe()

       customer_id         price   quantity
count    30.000000     30.000000  30.000000
mean     15.466667  15870.000000   1.433333
std       8.748333  24628.083913   0.626062
min       1.000000    450.000000   1.000000
25%       8.250000    725.000000   1.000000
50%      15.500000   1500.000000   1.000000
75%      22.750000  41050.000000   2.000000
max      29.000000  58000.000000   3.000000

In [52]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  30 non-null     int64
 1   name         30 non-null     str
 2   age          29 non-null     str
 3   city         28 non-null     str
 4   product      30 non-null     str
 5   price        30 non-null     int64
 6   quantity     30 non-null     int64
dtypes: int64(3), str(4)
memory usage: 1.8 KB

In [53]:
df.isnull().sum()

customer_id    0
name           0
age            1
city           2
product        0
price          0
quantity       0
dtype: int64

In [55]:
df["city"]=df["city"].fillna("unknown")
df

    customer_id     name  age        city     product  price  quantity
0             1     Arun   23     Chennai      Laptop  55000         1
1             2    Kumar   27       Salem       Mouse    500         2
2             3    Divya   22  Coimbatore    Keyboard   1500         1
3             4     Ravi   29     Madurai      Laptop  54000         1
4             5    Priya  NaN     Chennai  Headphones   2000         2
5             6    Manoj   31     unknown       Mouse    450         3
6             7   Anitha   26       Salem    Keyboard   1400         1
7             8   Suresh   28       Erode      Laptop  56000         1
8             9  Karthik          Chennai       Mouse    500         2
9            10    Nisha   23     Madurai  Headphones   2100         1
10           11    Arjun   30  Coimbatore      Laptop  57000         1
11           12    Deepa   25       Erode       Mouse    450         2
12           13    Vijay   27       Salem    Keyboard   1500         1
13           14  Lakshmi   29     Chennai  Headphones   2200         2
14           15      Ram   32     unknown      Laptop  58000         1
15           16    Sneha   24     Madurai       Mouse    500         3
16           17    Kiran   26       Erode    Keyboard   1400         1
17           18    Meena   28       Salem      Laptop  55000         1
18           19  Prakash   31  Coimbatore  Headphones   2000         1
19           20      Anu   22     Chennai       Mouse    450         2
20           21    Varun   27   Madururai    Keyboard   1500         1
21           22  Keerthi   23       Erode  Headphones   2100         1
22           23  Sathish   29       Salem      Laptop  56000         1
23           24    Pooja   24     Chennai       Mouse    500         2
24           25    Gokul   30  Coimbatore    Keyboard   1400         1
25           26    Rekha   26     Madurai  Headphones   2200         2
26           27   Murali   31       Erode      Laptop  57000         1
27           28  Shalini   25      Salem        Mouse    450         2
28           29   Naveen   28     Chennai    Keyboard   1500         1
29           29   Naveen   28     Chennai    Keyboard   1500         1

In [65]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  100 non-null    int64
 1   name         100 non-null    str
 2   age          71 non-null     object
 3   city         87 non-null     str
 4   product      100 non-null    str
 5   price        100 non-null    int64
 6   quantity     100 non-null    int64
dtypes: int64(3), object(1), str(3)
memory usage: 5.6+ KB

In [67]:
df["age"]=pd.to_numeric(df["age"],errors="coerce")
df.head()

   customer_id     name   age     city   product  price  quantity
0            1  Karthik   NaN      NaN    Laptop   1500         3
1            2    Meena   NaN  Madurai     Mouse  56000         2
2            3    Kiran   NaN      NaN     Mouse   2000         2
3            4    Divya   NaN      NaN     Mouse  56000         1
4            5    Kumar  29.0  Chennai  Keyboard   2000         3

In [71]:
df.isnull().sum()

customer_id     0
name            0
age            63
city           13
product         0
price           0
quantity        0
dtype: int64

In [72]:
df["age"]=df["age"].fillna(df["age"].mean())
df.head()

   customer_id     name        age     city   product  price  quantity
0            1  Karthik  25.432432      NaN    Laptop   1500         3
1            2    Meena  25.432432  Madurai     Mouse  56000         2
2            3    Kiran  25.432432      NaN     Mouse   2000         2
3            4    Divya  25.432432      NaN     Mouse  56000         1
4            5    Kumar  29.000000  Chennai  Keyboard   2000         3

In [73]:
df["city"]=df["city"].fillna("unknown")
df.head()

   customer_id     name        age     city   product  price  quantity
0            1  Karthik  25.432432  unknown    Laptop   1500         3
1            2    Meena  25.432432  Madurai     Mouse  56000         2
2            3    Kiran  25.432432  unknown     Mouse   2000         2
3            4    Divya  25.432432  unknown     Mouse  56000         1
4            5    Kumar  29.000000  Chennai  Keyboard   2000         3

In [74]:
df.isnull().sum()

customer_id    0
name           0
age            0
city           0
product        0
price          0
quantity       0
dtype: int64

In [75]:
df

    customer_id     name        age     city     product  price  quantity
0             1  Karthik  25.432432  unknown      Laptop   1500         3
1             2    Meena  25.432432  Madurai       Mouse  56000         2
2             3    Kiran  25.432432  unknown       Mouse   2000         2
3             4    Divya  25.432432  unknown       Mouse  56000         1
4             5    Kumar  29.000000  Chennai    Keyboard   2000         3
..          ...      ...        ...      ...         ...    ...       ...
95           96  Prakash  25.432432    Salem      Laptop   1500         1
96           97    Divya  25.432432    Erode  Headphones   2000         2
97           98      Ram  25.432432  Madurai       Mouse   2000         3
98           99    Deepa  18.000000    Salem    Keyboard  55000         1
99          100  Lakshmi  30.000000    Salem  Headphones   1500         1

[100 rows x 7 columns]

In [78]:
df.drop_duplicates()

    customer_id     name        age     city     product  price  quantity
0             1  Karthik  25.432432  unknown      Laptop   1500         3
1             2    Meena  25.432432  Madurai       Mouse  56000         2
2             3    Kiran  25.432432  unknown       Mouse   2000         2
3             4    Divya  25.432432  unknown       Mouse  56000         1
4             5    Kumar  29.000000  Chennai    Keyboard   2000         3
..          ...      ...        ...      ...         ...    ...       ...
95           96  Prakash  25.432432    Salem      Laptop   1500         1
96           97    Divya  25.432432    Erode  Headphones   2000         2
97           98      Ram  25.432432  Madurai       Mouse   2000         3
98           99    Deepa  18.000000    Salem    Keyboard  55000         1
99          100  Lakshmi  30.000000    Salem  Headphones   1500         1

[100 rows x 7 columns]

In [79]:
df.describe()

       customer_id         age         price    quantity
count   100.000000  100.000000    100.000000  100.000000
mean     50.500000   25.432432  28715.000000    2.050000
std      29.011492    3.289225  27512.554985    0.821123
min       1.000000   18.000000    500.000000    1.000000
25%      25.750000   25.432432   1500.000000    1.000000
50%      50.500000   25.432432  28500.000000    2.000000
75%      75.250000   25.432432  56000.000000    3.000000
max     100.000000   34.000000  57000.000000    3.000000

In [82]:
df["city"]=df["city"].replace("",pd.NA).fillna("unknown")
df

    customer_id     name        age     city     product  price  quantity
0             1  Karthik  25.432432  unknown      Laptop   1500         3
1             2    Meena  25.432432  Madurai       Mouse  56000         2
2             3    Kiran  25.432432  unknown       Mouse   2000         2
3             4    Divya  25.432432  unknown       Mouse  56000         1
4             5    Kumar  29.000000  Chennai    Keyboard   2000         3
..          ...      ...        ...      ...         ...    ...       ...
95           96  Prakash  25.432432    Salem      Laptop   1500         1
96           97    Divya  25.432432    Erode  Headphones   2000         2
97           98      Ram  25.432432  Madurai       Mouse   2000         3
98           99    Deepa  18.000000    Salem    Keyboard  55000         1
99          100  Lakshmi  30.000000    Salem  Headphones   1500         1

[100 rows x 7 columns]

In [83]:
df["city"]=df["city"].replace("Madururai","Madurai")

In [84]:
df["city"]=df["city"].str.strip()

In [86]:
df.to_csv("clean_customer_dataset.csv")